import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import mongoose from 'mongoose';
import { restaurants } from './seed.js';
import { Restaurant } from './models.js';

const app = express(); const secret = process.env.JWT_SECRET || 'menuqr-development-secret';
app.use(cors()); app.use(express.json());
let mongoReady = false;
if (process.env.MONGODB_URI) mongoose.connect(process.env.MONGODB_URI).then(async () => { if (await Restaurant.countDocuments() === 0) await Restaurant.insertMany(restaurants); mongoReady = true; console.log('MongoDB connected'); }).catch(error => console.error('MongoDB unavailable; using local seed data:', error.message));
const normalise = restaurant => { const r = restaurant.toObject ? restaurant.toObject() : restaurant; return { ...r, id:r.id || r.slug, itemCount:(r.items || []).length }; };
const allRestaurants = async () => mongoReady ? (await Restaurant.find().lean()).map(normalise) : restaurants;
const restaurantById = async id => (await allRestaurants()).find(r => r.id === id || r.slug === id);
const sign = () => jwt.sign({ role:'admin', email:'admin@menuqr.local' }, secret, { expiresIn:'8h' });
const requireAdmin = (req,res,next) => { try { jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret); next(); } catch { res.status(401).json({message:'Admin authentication required'}); } };
app.get('/api/health', (_,res)=>res.json({status:'ok'}));
app.post('/api/auth/login', async (req,res)=>{ const ok=req.body.email==='admin@menuqr.local' && req.body.password==='MenuQR123!'; if(!ok)return res.status(401).json({message:'Invalid email or password'}); res.json({token:sign(), user:{email:req.body.email,role:'admin'}}); });
app.get('/api/restaurants', async (_,res)=>res.json((await allRestaurants()).map(({items,...r})=>r)));
app.get('/api/restaurants/:id/menu', async (req,res)=>{const r=await restaurantById(req.params.id);if(!r)return res.status(404).json({message:'Restaurant not found'});res.json({restaurant:{id:r.id,slug:r.slug,name:r.name,tagline:r.tagline,address:r.address,phone:r.phone},categories:r.categories.map(name=>({name})),items:r.items});});
app.post('/api/restaurants', requireAdmin, (req,res)=>{const slug=req.body.slug||req.body.name?.toLowerCase().replace(/[^a-z0-9]+/g,'-'); if(!req.body.name||restaurants.some(r=>r.slug===slug))return res.status(400).json({message:'A unique restaurant name is required'});const r={id:slug,slug,name:req.body.name,tagline:req.body.tagline||'Welcome to our menu.',address:req.body.address||'',phone:req.body.phone||'',cuisine:req.body.cuisine||'',categories:[],items:[],itemCount:0};restaurants.push(r);res.status(201).json(r);});
app.put('/api/restaurants/:id', requireAdmin, async (req,res)=>{if(mongoReady){const r=await Restaurant.findOneAndUpdate({slug:req.params.id},req.body,{new:true}).lean();if(!r)return res.status(404).json({message:'Restaurant not found'});return res.json(normalise(r));}const r=restaurants.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({message:'Restaurant not found'});Object.assign(r,req.body);r.itemCount=r.items.length;res.json(r);});
app.post('/api/restaurants/:id/items', requireAdmin, async (req,res)=>{const item={id:`${req.params.id}-${Date.now()}`,...req.body,available:req.body.available!==false};if(mongoReady){const r=await Restaurant.findOneAndUpdate({slug:req.params.id},{$push:{items:item}},{new:true}).lean();if(!r)return res.status(404).json({message:'Restaurant not found'});return res.status(201).json({item,restaurant:normalise(r)});}const r=restaurants.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({message:'Restaurant not found'});r.items.push(item);r.itemCount=r.items.length;res.status(201).json({item,restaurant:r});});
app.put('/api/restaurants/:id/items/:itemId', requireAdmin, async (req,res)=>{if(mongoReady){const r=await Restaurant.findOneAndUpdate({slug:req.params.id,'items.id':req.params.itemId},{$set:Object.fromEntries(Object.entries(req.body).map(([key,value])=>[`items.$.${key}`,value]))},{new:true}).lean();if(!r)return res.status(404).json({message:'Dish not found'});return res.json(normalise(r));}const r=restaurants.find(x=>x.id===req.params.id);const item=r?.items.find(x=>x.id===req.params.itemId);if(!item)return res.status(404).json({message:'Dish not found'});Object.assign(item,req.body);res.json(r);});
app.delete('/api/restaurants/:id/items/:itemId', requireAdmin, async (req,res)=>{if(mongoReady){const r=await Restaurant.findOneAndUpdate({slug:req.params.id},{$pull:{items:{id:req.params.itemId}}},{new:true}).lean();if(!r)return res.status(404).json({message:'Restaurant not found'});return res.json(normalise(r));}const r=restaurants.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({message:'Restaurant not found'});r.items=r.items.filter(x=>x.id!==req.params.itemId);r.itemCount=r.items.length;res.json(r);});
app.delete('/api/restaurants/:id', requireAdmin, (req,res)=>{const i=restaurants.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({message:'Restaurant not found'});restaurants.splice(i,1);res.status(204).end();});
app.get('/api/restaurants/:restaurantId/categories', (req,res)=>{const r=restaurants.find(x=>x.id===req.params.restaurantId);if(!r)return res.status(404).json({message:'Restaurant not found'});res.json(r.categories.map(name=>({name})));});
app.get('/api/restaurants/:restaurantId/items', (req,res)=>{const r=restaurants.find(x=>x.id===req.params.restaurantId);if(!r)return res.status(404).json({message:'Restaurant not found'});res.json(r.items);});
app.listen(process.env.PORT||4000, ()=>console.log('MenuQR API running on http://localhost:4000'));
